apiVersion: v1
kind: ConfigMap
metadata:
  name: multi-juicer-config
  labels:
    {{- include "multi-juicer.labels" . | nindent 4 }}
data:
  config.json: |

    {{
      (merge .Values.config (dict "cookie" (dict "name" .Values.cookie.name "secure" .Values.cookie.secure))) | toPrettyJson | nindent 6
    }}
