apiVersion: v1
kind: Service
metadata:
  name: multijuicer-private
  labels:
    {{- include "multi-juicer.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{ include "multi-juicer.selectorLabels" . | nindent 4 }}
  ports:
    - port: 8082
      name: private
      targetPort: private
