apiVersion: v1
kind: Secret
metadata:
  name: multi-juicer-secret
  labels:
    {{- include "multi-juicer.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.cookie.cookieParserSecret }}
  cookieParserSecret: {{ .Values.cookie.cookieParserSecret | b64enc | quote }}
  {{- else }}
  cookieParserSecret: {{ randAlphaNum 24 | b64enc | quote }}
  {{- end }}
  {{- if .Values.adminPassword }}
  adminPassword: {{ .Values.adminPassword | b64enc | quote }}
  {{- else }}
  adminPassword: {{ randAlphaNum 24 | upper | b64enc | quote }}
  {{- end }}
