# https://taskfile.dev
version: "3"

tasks:
  dev:
    aliases: [d]
    desc: |
      Builds and Deploys MultiJuicer to the default kubernetes context.
      Then forwards the balancer service to localhost:8080
    cmds:
      - ./build-and-deploy.sh
      - kubectl rollout status deployment balancer
      - kubectl port-forward deployment/balancer 8080:8080

  build:
    aliases: [b]
    cmds:
      - task: balancer:ui:build

  lint:
    aliases: [l]
    cmds:
      - task: cleaner:lint
      - task: balancer:api:lint
      - task: progress-watchdog:lint
      - task: balancer:ui:lint

  lint:fix:
    desc: Runs the linters which support auto fixing errors
    aliases: [lf]
    cmds:
      - task: balancer:ui:lint:fix

  test:
    aliases: [t]
    cmds:
      - task: helm:test
      - task: balancer:ui:test
      - task: balancer:api:test
      - task: cleaner:test
      - task: progress-watchdog:test

  balancer:ui:build:
    preconditions:
      - sh: test -d node_modules/
        msg: "balancer ui dependencies are not installed. run 'npm ci' in balancer/ui/ to install them."
    cmds:
      - npm run build
    dir: balancer/ui/

  balancer:ui:lint:
    preconditions:
      - sh: test -d node_modules/
        msg: "balancer ui dependencies are not installed. run 'npm ci' in balancer/ui/ to install them."
    cmds:
      - npm run lint
    dir: balancer/ui/

  balancer:ui:lint:fix:
    preconditions:
      - sh: test -d node_modules/
        msg: "balancer ui dependencies are not installed. run 'npm ci' in balancer/ui/ to install them."
    cmds:
      - npm run lint:fix
    dir: balancer/ui/

  balancer:ui:bundle-analyzer:
    preconditions:
      - sh: test -d node_modules/
        msg: "balancer ui dependencies are not installed. run 'npm ci' in balancer/ui/ to install them."
    cmds:
      - npx vite-bundle-visualizer
    dir: balancer/ui/

  balancer:ui:test:
    preconditions:
      - sh: test -d node_modules/
        msg: "balancer ui dependencies are not installed. run 'npm ci' in balancer/ui/ to install them."
    cmds:
      - |
        # run with bun if installed, otherwise use npm
        if command -v bun &> /dev/null; then
          bun run test -- --run
        else
          npm test -- --run
        fi
    dir: balancer/ui/

  balancer:api:test:
    preconditions:
      - sh: test -f ui/build/index.html
        msg: "juice balancer ui needs to be compiled for the api tests to work properly. run 'task build' to compile it."
    cmds:
      - go test ./...
    dir: balancer/

  balancer:api:lint:
    preconditions:
      - sh: which staticcheck
        msg: "staticcheck needs to be installed for running the balancer api linter."
    cmds:
      - go vet ./...
      - staticcheck ./...
    dir: balancer/

  progress-watchdog:test:
    preconditions:
      - sh: which go
        msg: "go needs to be installed for running the progress-watchdog tests."
    cmds:
      - go test ./...
    dir: progress-watchdog/

  progress-watchdog:lint:
    preconditions:
      - sh: which staticcheck
        msg: "staticcheck needs to be installed for running the progress-watchdog linter."
    cmds:
      - go vet ./...
      - staticcheck ./...
    dir: progress-watchdog/

  cleaner:test:
    cmds:
      - go test ./...
    dir: cleaner/

  cleaner:lint:
    preconditions:
      - sh: which staticcheck
        msg: "staticcheck needs to be installed for running the cleaner linter."
    cmds:
      - go vet ./...
      - staticcheck ./...
    dir: cleaner/

  helm:test:
    preconditions:
      - sh: helm version
        msg: "helm is not installed: https://helm.sh/"
      - sh: helm unittest --help
        msg: "helm unittest plugin is not installed: https://github.com/helm-unittest/helm-unittest/"
    cmds:
      - helm unittest .
    dir: helm/multi-juicer/

  helm:test:update-snapshots:
    preconditions:
      - sh: helm version
        msg: "helm is not installed: https://helm.sh/"
      - sh: helm unittest --help
        msg: "helm unittest plugin is not installed: https://github.com/helm-unittest/helm-unittest/"
    cmds:
      - helm unittest . --update-snapshot
    dir: helm/multi-juicer/

  e2e:setup:
    desc: Create and setup KinD cluster for E2E testing
    aliases: [e2e:setup-kind]
    dir: test/e2e
    cmds:
      - make setup-kind

  e2e:install:
    desc: Install MultiJuicer in KinD cluster for E2E testing
    aliases: [e2e:install-multi-juicer]
    dir: test/e2e
    cmds:
      - make install-multi-juicer

  e2e:port-forward:
    desc: Setup port forwarding for E2E tests (localhost:8080)
    dir: test/e2e
    cmds:
      - make port-forward

  e2e:test:
    desc: Run E2E tests against Kubernetes cluster
    aliases: [e2e]
    dir: test/e2e
    cmds:
      - make run-tests

  e2e:logs:
    desc: View E2E test environment logs and status
    dir: test/e2e
    cmds:
      - make logs

  e2e:cleanup:
    desc: Delete KinD cluster and cleanup E2E environment
    dir: test/e2e
    cmds:
      - make cleanup

  e2e:all:
    desc: Complete E2E test setup and execution (requires port-forward in separate terminal)
    dir: test/e2e
    cmds:
      - make setup-kind
      - make install-multi-juicer
      - echo "Port forwarding started in background. Run 'task e2e:test' in another terminal to run tests."
      - make port-forward
