# https://taskfile.dev
version: "3"

tasks:
  dev:
    aliases: [d]
    desc: |
      Builds and Deploys MultiJuicer to the default kubernetes context.
      Then forwards the balancer service to localhost:8080
    cmds:
      - task: build-and-deploy
      - kubectl rollout status deployment balancer
      - kubectl port-forward deployment/balancer 8080:8080

  build-and-deploy:
    desc: |
      Builds all MultiJuicer components and installs them to a local kubernetes cluster.
      For this to work the local kubernetes cluster must have access to the same local registry / image cache which 'docker build ...' writes its image to.
      For example docker-desktop with its included k8s cluster.
    vars:
      VERSION: '{{uuid}}'
    cmds:
      - |
        docker build --progress quiet -f containers/cleaner/Dockerfile -t local/cleaner:{{.VERSION}} . &
        docker build --progress quiet -f containers/progress-watchdog/Dockerfile -t local/progress-watchdog:{{.VERSION}} . &
        docker build --progress quiet -f containers/balancer/Dockerfile -t local/balancer:{{.VERSION}} . &
        wait
      - |
        if [ "$(kubectl config current-context)" = "kind-kind" ]; then
          kind load docker-image "local/progress-watchdog:{{.VERSION}}" &
          kind load docker-image "local/cleaner:{{.VERSION}}" &
          kind load docker-image "local/balancer:{{.VERSION}}" &
          wait
        fi
      - |
        helm upgrade --install multi-juicer ./helm/multi-juicer \
          --set="imagePullPolicy=IfNotPresent" \
          --set="balancer.repository=local/balancer" \
          --set="balancer.tag={{.VERSION}}" \
          --set="progressWatchdog.repository=local/progress-watchdog" \
          --set="progressWatchdog.tag={{.VERSION}}" \
          --set="juiceShopCleanup.repository=local/cleaner" \
          --set="juiceShopCleanup.tag={{.VERSION}}" \
          --set="balancer.cookie.cookieParserSecret=dev-secret"

  build:
    aliases: [b]
    cmds:
      - task: ui:build

  lint:
    aliases: [l]
    cmds:
      - task: go:lint
      - task: ui:lint

  lint:fix:
    desc: Runs the linters which support auto fixing errors
    aliases: [lf]
    cmds:
      - task: go:lint
      - task: ui:lint:fix

  test:
    aliases: [t]
    cmds:
      - task: helm:test
      - task: ui:test
      - task: go:test
      - task: semgrep:scan

  semgrep:scan:
    preconditions:
      - sh: which semgrep
        msg: "semgrep is not installed. Install it from https://semgrep.dev/ to run static analysis scanning."
    cmds:
      - semgrep scan --config=auto --quiet

  ui:build:
    preconditions:
      - sh: test -d node_modules/
        msg: "ui dependencies are not installed. run 'npm ci' in ui/ to install them."
    cmds:
      - npm run build
    dir: ui/

  ui:lint:
    preconditions:
      - sh: test -d node_modules/
        msg: "ui dependencies are not installed. run 'npm ci' in ui/ to install them."
    cmds:
      - npm run lint
    dir: ui/

  ui:lint:fix:
    preconditions:
      - sh: test -d node_modules/
        msg: "ui dependencies are not installed. run 'npm ci' in ui/ to install them."
    cmds:
      - npm run lint:fix
    dir: ui/

  ui:bundle-analyzer:
    preconditions:
      - sh: test -d node_modules/
        msg: "ui dependencies are not installed. run 'npm ci' in ui/ to install them."
    cmds:
      - npx vite-bundle-visualizer
    dir: ui/

  ui:test:
    preconditions:
      - sh: test -d node_modules/
        msg: "ui dependencies are not installed. run 'npm ci' in ui/ to install them."
    cmds:
      - |
        # run with bun if installed, otherwise use npm
        if command -v bun &> /dev/null; then
          bun run test -- --run
        else
          npm test -- --run
        fi
    dir: ui/

  go:test:
    preconditions:
      - sh: test -f ui/build/index.html
        msg: "ui needs to be compiled for the api tests to work properly. run 'task build' to compile it."
    cmds:
      - go test -cover ./...

  go:lint:
    preconditions:
      - sh: which staticcheck
        msg: "staticcheck needs to be installed for running the go linter."
    cmds:
      - go fmt ./...
      - go fix ./...
      - go vet ./...
      - staticcheck ./...

  helm:test:
    preconditions:
      - sh: helm version
        msg: "helm is not installed: https://helm.sh/"
      - sh: helm unittest --help
        msg: "helm unittest plugin is not installed: https://github.com/helm-unittest/helm-unittest/"
    cmds:
      - helm unittest .
    dir: helm/multi-juicer/

  helm:docs:
    preconditions:
      - sh: helm-docs --version
        msg: "helm-docs is not installed: https://github.com/norwoodj/helm-docs"
    cmds:
      - helm-docs .
    dir: helm/multi-juicer/

  helm:test:update-snapshots:
    preconditions:
      - sh: helm version
        msg: "helm is not installed: https://helm.sh/"
      - sh: helm unittest --help
        msg: "helm unittest plugin is not installed: https://github.com/helm-unittest/helm-unittest/"
    cmds:
      - helm unittest . --update-snapshot
    dir: helm/multi-juicer/
