apiVersion: v1
kind: Secret
metadata:
  name: juice-balancer-secret
  labels:
    {{- include "multi-juicer.juice-balancer.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.balancer.cookie.cookieParserSecret }}
  cookieParserSecret: {{ .Values.balancer.cookie.cookieParserSecret | b64enc | quote }}
  {{- else }}
  cookieParserSecret: {{ randAlphaNum 24 | b64enc | quote }}
  {{- end }}
  {{- if .Values.balancer.adminPassword }}
  adminPassword: {{ .Values.balancer.adminPassword | b64enc | quote }}
  {{- else }}
  adminPassword: {{ randAlphaNum 8 | upper | b64enc | quote }}
  {{- end }}
  {{- if .Values.balancer.metrics.enabled }}
  metricsBasicAuthUsername: {{ .Values.balancer.metrics.basicAuth.username | b64enc | quote }}
  metricsBasicAuthPassword: {{ .Values.balancer.metrics.basicAuth.password | b64enc | quote }}
  {{- end }}
