apiVersion: v1
kind: ConfigMap
metadata:
  name: juice-shop-config
  labels:
    {{- include "multi-juicer.juice-shop.labels" . | nindent 4 }}
data:
  multi-juicer.yaml: |-
    {{- $config := deepCopy .Values.config.juiceShop.config }}
    {{- if .Values.config.juiceShop.llm.enabled }}
    {{- $chatBot := dict "chatBot" (dict "model" .Values.config.juiceShop.llm.model "llmApiUrl" (printf "http://multijuicer-llm-gateway.%s.svc.cluster.local:8082" .Release.Namespace)) }}
    {{- $_ := merge ($config).application $chatBot }}
    {{- end }}
    {{ $config | toYaml | nindent 4 }}
