apiVersion: v1
kind: Service
metadata:
  name: multijuicer-internal
  labels:
    {{- include "multi-juicer.balancer.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{ include "multi-juicer.balancer.selectorLabels" . | nindent 4 }}
  ports:
    - port: 8082
      name: internal
      targetPort: internal
