on: [push, pull_request]
name: "Tests"
permissions:
  contents: read
jobs:
  go:
    name: Go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: "go.mod"
          cache-dependency-path: "go.sum"
      - name: "Place index.html file into ui build folder"
        run: |
          mkdir -p ui/build/
          cp ui/index.html ui/build/index.html
      - name: "Ensure go code is properly formatted"
        run: |
          unformatted=$(go fmt ./...)
          if [ -n "$unformatted" ]; then
            echo "::error::The following files are not properly formatted: $unformatted"
            echo "Run 'go fmt ./...' to fix."
            exit 1
          fi
      - name: "Ensure go code is properly modernized / fixed"
        run: |
          go fix ./...
          if ! git diff --exit-code; then
            echo "::error::go fix produced changes. Run 'go fix ./...' to fix."
            exit 1
          fi
      - name: "Lint"
        run: go vet ./...
      - name: "Staticcheck"
        run: go tool staticcheck ./...
      - name: "go-critic"
        run: go tool gocritic check ./...
      - name: "Test"
        run: go test -cover ./...

  ui:
    name: UI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "lts/*"
      - name: "Install dependencies"
        run: npm ci --ignore-scripts
      - name: "Lint"
        run: npm run lint
      - name: "Test"
        run: npm run test -- --run

  semgrep:
    name: Semgrep
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: "Run Semgrep"
        run: semgrep scan --config=auto

  helm:
    name: Helm
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: helm/multi-juicer/
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Verify tools
        run: |
          helm version
      - name: Install Helm Unit Test Plugin
        run: |
          helm plugin install https://github.com/helm-unittest/helm-unittest.git --version 1.0.3
      - name: Helm-Chart Unit Tests
        run: helm unittest .
