name: "Update news on owasp-juice.shop"

on:
  release:
    types: [ published ]

# the pipeline doesn't use the GITHUB_TOKEN for anything, so no permissions needed.
permissions: {}

jobs:
  UpdateNewsOnWebsite:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.BOT_TOKEN }}
          repository: OWASP/www-project-juice-shop
          ref: master
      - name: Update tab_news.md
        run: |
          sed -i 's/<!-- next:multi-juicer -->/<!-- next:multi-juicer -->\n* ${{ github.event.release.published_at }}: multi-juicer [`${{ github.event.release.tag_name }}`](https:\/\/github.com\/juice-shop\/multi-juicer\/releases\/tag\/${{ github.event.release.tag_name }})/' tab_news.md
      - uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0 #v6.0.1
        with:
          commit_message: "Add multi-juicer ${{ github.event.release.tag_name }} release notes to tab_news.md"
          branch: master
          commit_options: '--signoff'

          # Optional commit user and author settings
          commit_user_name: JuiceShopBot
          commit_user_email: 61591748+JuiceShopBot@users.noreply.github.com
          commit_author: JuiceShopBot <61591748+JuiceShopBot@users.noreply.github.com>
